var Charting = MindFusion.Charting;
var Collections = Charting.Collections;
var Controls = Charting.Controls;
var Series2D = Charting.Series2D;
var SimpleSeries = Charting.SimpleSeries;
var PieSeries = Charting.PieSeries;
var BarSeries = Charting.BarSeries;
var ToolTip = Charting.ToolTip;

var seriesList = new Collections.ObservableCollection();
var n1 = new Collections.List();
n1.add(0);
n1.add(1);
n1.add(2);
n1.add(3);
var n2 = new Collections.List();
n2.add(25000);
n2.add(50000);
n2.add(40000);
n2.add(55000);
var s1 = new Collections.List();
s1.add("January");
s1.add("February");
s1.add("March");
s1.add("April");
// 2
var n11 = new Collections.List();
n11.add(0);
n11.add(1);
n11.add(2);
n11.add(3);
var n21 = new Collections.List();
n21.add(30000);
n21.add(70000);
n21.add(65000);
n21.add(15000);
var s11 = new Collections.List();
s11.add("May");
s11.add("June");
s11.add("July");
s11.add("August");
// 3
var n12 = new Collections.List();
n12.add(0);
n12.add(1);
n12.add(2);
n12.add(3);
var n22 = new Collections.List();
n22.add(25000);
n22.add(45000);
n22.add(35000);
n22.add(65000);
var s12 = new Collections.List();
s12.add("September");
s12.add("October");
s12.add("November");
s12.add("December");
var series = new Series2D(n1, n2, s1);
series.title = "Series 1";
seriesList.add(series);
var series1 = new Series2D(n11, n21, s11);
series1.title = "Series 2";
seriesList.add(series1);
var series2 = new Series2D(n12, n22, s12);
series2.title = "Series 3";
seriesList.add(series2);
var barSeries = new BarSeries(n21, new Collections.List(["iOne", "iTwo", "iThree", "iFour"]), new Collections.List(["oOne", "oTwo", "oThree", "oFour"]), new Collections.List(["xOne", "xTwo", "xThree", "xFour"]));
barSeries.title = "Bar Series";
var simpleSeries = new SimpleSeries(n22, new Collections.List(["iOne", "iTwo", "iThree", "iFour"]));
simpleSeries.title = "Line Series";
var pieSeries = new PieSeries(n2, new Collections.List(["iOne", "iTwo", "iThree", "iFour"]), new Collections.List(["oOne", "oTwo", "oThree", "oFour"]));
pieSeries.title = "Pie Series";

ToolTip.verticalPadding = 4;
ToolTip.horizontalPadding = 4;

var barChart = new Controls.BarChart(document.getElementById('barChart'));
barChart.series = new Collections.ObservableCollection([barSeries]);
var lineChart = new Controls.LineChart(document.getElementById('lineChart'));
lineChart.series = new Collections.ObservableCollection([simpleSeries]);
var pieChart = new Controls.PieChart(document.getElementById('pieChart'));
pieChart.series = pieSeries;
var lr = new Charting.LegendRenderer();
barChart.rootPanel.children.add(lr);
barChart.draw();